### ISSUE TITLE
Display gone during Tx

### ISSUE THREAD

**Issue by rai4424** [egzumer/uv-k5-firmware-custom#17]
A serious isue has been noticed in latest Version (V0.8) plz. Battery voltages drops immediately during Tx and resumes after. My Talkie's display vanished two times.  After that I installed stock firmware, there was no such issue.

**Comment by rai4424** [comment]
A number of videos recorded by me.

**Comment by rai4424** [comment]
I  have re-checked privious FWs, v.07, and v.06 were showing battery voltage drop issue while TX. So I m on v.04 with sad face.

**Comment by Yag00000** [comment]
battery drop is correct in TX in real time

**Comment by rai4424** [comment]
battery drop is correct in TX in real time , due to high consumption in TX

No its special case. Voltage drop in huge and display 
was glitching. Disply was totally white two times on 80% Battery. I have  recording but cant post hare.

**Comment by rai4424** [comment]
Screen shot 1

**Comment by rai4424** [comment]
Still not resolved the issue

**Comment by lohtse** [comment]
I use this formware and have been ysing custom daily builds for two weeks and NEVER once had the claimed issue....

**Comment by rai4424** [comment]
I use this formware and have been ysing custom daily builds for two weeks and NEVER once had the claimed issue....


This custom FW was released two days ago, how you are using it for two weeks?

**Comment by lohtse** [comment]
I made the effort to build/compile when new commits have been made..hence as stated custom build..I enable and add more then in statdard build so as a result would experince issues if tuere was any.

**Comment by lohtse** [comment]
I wonder it the issue you are experiencing is hardware related or due a conflict in the prebuilt FW  you are using.  Like I have already stated I have this Firmware running on my K5s(6 in total)  and not one has had issue as per here..  But I am using one I have compiled myself with all the latest's fixes etc.. SO that could actually be the reason why. Below is what I have  enabled 
![image](https://github.com/egzumer/uv-k5-firmware-custom/assets/48331155/60f7e342-67c5-430e-adb5-8f33fd7a6517)



This is what is enabled in prebuilt
![image](https://github.com/egzumer/uv-k5-firmware-custom/assets/48331155/2b6c8e75-2b5f-4beb-8294-5a3b7002ec3e)

**Comment by egzumer** [comment]
This commit [149a0f5](https://github.com/egzumer/uv-k5-firmware-custom/commit/149a0f5bdc962c93d073d9756e14f64ed1520e30) blocks voltage reading when radio is transmitting (like it used to be)

**Comment by rai4424** [comment]
> This commit [149a0f5](https://github.com/egzumer/uv-k5-firmware-custom/commit/149a0f5bdc962c93d073d9756e14f64ed1520e30) blocks voltage reading when radio is transmitting (like it used to be)

You are working great، I m waiting for v0.9 eagerly

**Comment by rai4424** [comment]
May be this issue woll be resolved in next version

**Comment by rai4424** [comment]
Thanks you very much
