### ISSUE TITLE
frequency steps rounding in VFO entry

### ISSUE THREAD

**Issue by gartnl** [egzumer/uv-k5-firmware-custom#180]
All firmwares, original or custom, round VFO to the nearest step value. Many times this is not what I want.
e.g. PMR FM starts at 446.006.250 with a step size of 12.5 kHz. I have to set the stepsize to 6.25 in order to enter this frequency. But than I have to step up twice to go to the next channel. And if I want to enter a random frequency I need to set stepsize to a low value.
Would it be possible to add an option to omit stepsize rounding in VFO mode when entering a frequency, and only add/substract the stepsize when using up/down buttons without rounding. That would make the VFO free to enter any frequency desired without the need to adjust  ( and re-adjust ) the stepsize. 
Perhaps this can be combined with issue #126, and make entering a frequency smarter altogether. Entering 446*00625M would signal I want that exact frequency, and set a flag to skip rounding on up/down button. Whereas the stock method of 446006 or just 446M would  set the flag to round to stepsize again with up/down. The * would indicate the method used in this proposal so no additional menu or button needs to be assigned.

**Comment by ErikS-web** [comment]
Why not turn your PMR-channels into Memory-channels

**Comment by ErikS-web** [comment]
This is a digital radio and intended for FM. So there is always a step. Normally 12.5 or 25 Khz for FM.

You're asking for step = 1 Khz. 

What could be usefull in Spectrum Analyzer only with USB.

**Comment by AsciiWolf** [comment]
Another possible solution should be to allow changing the frequency to 446.006.250 (by having step set to 6.25 kHz), then changing the step to 12.5 kHz. This is how I do it on my other radio running OpenGD77. The problem is that when I do this on Quansheng, the frequency seems to change to 446.000 MHz.

**Comment by g4eml** [comment]
The main issue here seems to be where a half channel offset is used. Although this is not common, it is used for some services as mentioned above.   Maybe a workable solution would be to adjust the rounding so that it rounds to half the current channel spacing. For example with 12.5 KHz channel steps it would also be possible enter a 6.25KHz offset channel.  The up and down arrow would then still step in 12.5Khz steps but would retain the 6.25Khz offset.

This would not apply to the 8.33 KHz steps, They already have a special rounding applied to match the aviation channel numbers.

**Comment by g4eml** [comment]
I have tried this solution on my build and it works very well. 
For channel spacings of 10KHz or greater divide the rounding step size by 2. This allows direct entry of half channel offsets but still retains the channel step size when using the up and down arrows. 
Step sizes less than 10KHz (1000) ending in odd numbers can't be divided by 2 so it makes no sense to apply the same division to those.

 In frequencies.c add one extra line to FREQUENCY_RoundToStep()

  if(step >= 1000) step = step/2;

**Comment by gartnl** [comment]
@g4eml  I was working along the same lines. It seems like a good compromise to me.
