### ISSUE TITLE
Headset-mode

### ISSUE THREAD

**Issue by dadanielat** [egzumer/uv-k5-firmware-custom#376]
Would it be possible to add a headset-mode? At the moment using a headset is nearly impossible, because of the loud popping noise when a channel is keyed up and the NF driver stage is activated. When enabled, the NF output should never be completely turned off, so you would hear the popping only once, the remaining static noise wouldn't be noticeable. I know this would limit battery life.

**Comment by ErikS-web** [comment]
What type of radio and what revision level of board (look inside) dou you have ?

**Comment by egzumer** [comment]
I myself am not going to add any headset mode, that is for sure.
I have no idea what the NF is. I don't know which popping you are talking about. I know there are cases when that happens, but which one do you mean?
Popping sound happens when audio commands are not executed in correct order. I know 1o11 did some corrections a while back, I didn't bother to port those.

**Comment by ErikS-web** [comment]
It also might be the "DC on the audio"-problem.
Lets wait for photo of internal of the radio.

**Comment by egzumer** [comment]
@dadanielat Ok, I see what you mean. I didn't think about that before. This is caused by the unfortunate quansheng design. The internal speaker is connected to both sides of the amplifier, so there is no pop. External speaker is only connected to one. This is a more shitty design than I thought.
I'll take a note of that, but I'm currently overloaded with other things.
