### ISSUE TITLE
Scrambler frequency below 3100 not usable

### ISSUE THREAD

**Issue by mentanah** [egzumer/uv-k5-firmware-custom#431]
Programmed three radios with v0.21:
Set channel with scrambler on to 2900Hz, for each radio at  446.08125 MHz.
Now you can her a loud hissing, squeaking noise while talking, approximately comparable like wrong selected scrambler frequency. Adjusting it above 3200 Hz on all devices results in clear scrambler decoding.

I don't know now, wether this is a hardware issue due to slightly frequency offsets of the xtal or a software one.

The fact, that at higher scrambler frequencies everything works well, might point to a software issue, maybe due to rounding in some calculations?

Can anybody reproduce and confirm?

**Comment by ea7hjb** [comment]
I noted this problem since the first days of Quansheng, even with the original firmware. I tested it vs many brands (Motorola, Vertex, etc) and while I haven't been unable to reproduce exactly when or how it occurs, it happens a lot.

I think it is related to the CTCSS/DCS, as you can hear the subtone after the inverter processing as a continuos "biiiip" if analog, or "bip bip bip" if DCS. If you can, repeat the test with the transmitter using no subtone at all.

**Comment by mentanah** [comment]
> I noted this problem since the first days of Quansheng, even with the original firmware. I tested it vs many brands (Motorola, Vertex, etc) and while I haven't been unable to reproduce exactly when or how it occurs, it happens a lot.
> 
> I think it is related to the CTCSS/DCS, as you can hear the subtone after the inverter processing as a continuos "biiiip" if analog, or "bip bip bip" if DCS. If you can, repeat the test with the transmitter using no subtone at all.

Shure, that's it! Thank you for this good explanation. Since the DTMF must not be scrambled, it is not "encoded" but "decoded" as well.

**Comment by mentanah** [comment]
Closed as good explanation is delivered.
