### ISSUE TITLE
Sensitivity loss

### ISSUE THREAD

**Issue by rai4424** [egzumer/uv-k5-firmware-custom#48]
My radio is not receiving weak signals
Its may be because of broken AGC.

**Comment by egzumer** [comment]
For the future this kind of vague description is useless, no information on what frequency, compared to what firmware. You could at least say where did you get this information from, because it doesn't seem like you found out that "AGC is broken" on your own.
From what I know so far AGC was never used, because it probably didn't work as expected. Also it seems that it brakes the AM fix.
