### ISSUE TITLE
Loud pop through headset when squelch opens

### ISSUE THREAD

**Issue by loncaric** [egzumer/uv-k5-firmware-custom#549]
On v0.22 when I plug in an external headset each transmission is proceeded by a loud pop when squelch is broken.

**Comment by salokinrekced** [comment]
I believe this is more to do with a hardware issue of the PA turning on and off. UV5R has a similar issue.

**Comment by egzumer** [comment]
Yes that is the case. It is especially due to external speaker being connected to one side of the PA differential output. The other side of the speaker is connected to ground. When PA is activated the outputs are switched from 0V to 1/2 supply voltage. That is where the pop comes from. There was a suggestion to keep PA active all the time, but this would greatly rise power consumption.

There is nothing I can do about that.
